/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DamnificadosInformalRouteImport } from './routes/damnificados.informal'

const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DamnificadosInformalRoute = DamnificadosInformalRouteImport.update({
  id: '/damnificados/informal',
  path: '/damnificados/informal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/damnificados/informal': typeof DamnificadosInformalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/damnificados/informal': typeof DamnificadosInformalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/damnificados/informal': typeof DamnificadosInformalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/empresas' | '/damnificados/informal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/empresas' | '/damnificados/informal'
  id: '__root__' | '/' | '/empresas' | '/damnificados/informal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresasRoute: typeof EmpresasRoute
  DamnificadosInformalRoute: typeof DamnificadosInformalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damnificados/informal': {
      id: '/damnificados/informal'
      path: '/damnificados/informal'
      fullPath: '/damnificados/informal'
      preLoaderRoute: typeof DamnificadosInformalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresasRoute: EmpresasRoute,
  DamnificadosInformalRoute: DamnificadosInformalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
