/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DamnificadosIndexRouteImport } from './routes/damnificados.index'
import { Route as DamnificadosInformalRouteImport } from './routes/damnificados.informal'
import { Route as DamnificadosCandidatoRouteImport } from './routes/damnificados.candidato'
import { Route as ApiPublicCandidatosRouteImport } from './routes/api/public/candidatos'
import { Route as ApiPublicCvSubmissionIdFilenameRouteImport } from './routes/api/public/cv.$submissionId.$filename'

const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DamnificadosIndexRoute = DamnificadosIndexRouteImport.update({
  id: '/damnificados/',
  path: '/damnificados/',
  getParentRoute: () => rootRouteImport,
} as any)
const DamnificadosInformalRoute = DamnificadosInformalRouteImport.update({
  id: '/damnificados/informal',
  path: '/damnificados/informal',
  getParentRoute: () => rootRouteImport,
} as any)
const DamnificadosCandidatoRoute = DamnificadosCandidatoRouteImport.update({
  id: '/damnificados/candidato',
  path: '/damnificados/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCandidatosRoute = ApiPublicCandidatosRouteImport.update({
  id: '/api/public/candidatos',
  path: '/api/public/candidatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCvSubmissionIdFilenameRoute =
  ApiPublicCvSubmissionIdFilenameRouteImport.update({
    id: '/api/public/cv/$submissionId/$filename',
    path: '/api/public/cv/$submissionId/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/guia': typeof GuiaRoute
  '/damnificados/candidato': typeof DamnificadosCandidatoRoute
  '/damnificados/informal': typeof DamnificadosInformalRoute
  '/damnificados/': typeof DamnificadosIndexRoute
  '/api/public/candidatos': typeof ApiPublicCandidatosRoute
  '/api/public/cv/$submissionId/$filename': typeof ApiPublicCvSubmissionIdFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/guia': typeof GuiaRoute
  '/damnificados/candidato': typeof DamnificadosCandidatoRoute
  '/damnificados/informal': typeof DamnificadosInformalRoute
  '/damnificados': typeof DamnificadosIndexRoute
  '/api/public/candidatos': typeof ApiPublicCandidatosRoute
  '/api/public/cv/$submissionId/$filename': typeof ApiPublicCvSubmissionIdFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/guia': typeof GuiaRoute
  '/damnificados/candidato': typeof DamnificadosCandidatoRoute
  '/damnificados/informal': typeof DamnificadosInformalRoute
  '/damnificados/': typeof DamnificadosIndexRoute
  '/api/public/candidatos': typeof ApiPublicCandidatosRoute
  '/api/public/cv/$submissionId/$filename': typeof ApiPublicCvSubmissionIdFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresas'
    | '/guia'
    | '/damnificados/candidato'
    | '/damnificados/informal'
    | '/damnificados/'
    | '/api/public/candidatos'
    | '/api/public/cv/$submissionId/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresas'
    | '/guia'
    | '/damnificados/candidato'
    | '/damnificados/informal'
    | '/damnificados'
    | '/api/public/candidatos'
    | '/api/public/cv/$submissionId/$filename'
  id:
    | '__root__'
    | '/'
    | '/empresas'
    | '/guia'
    | '/damnificados/candidato'
    | '/damnificados/informal'
    | '/damnificados/'
    | '/api/public/candidatos'
    | '/api/public/cv/$submissionId/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresasRoute: typeof EmpresasRoute
  GuiaRoute: typeof GuiaRoute
  DamnificadosCandidatoRoute: typeof DamnificadosCandidatoRoute
  DamnificadosInformalRoute: typeof DamnificadosInformalRoute
  DamnificadosIndexRoute: typeof DamnificadosIndexRoute
  ApiPublicCandidatosRoute: typeof ApiPublicCandidatosRoute
  ApiPublicCvSubmissionIdFilenameRoute: typeof ApiPublicCvSubmissionIdFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damnificados/': {
      id: '/damnificados/'
      path: '/damnificados'
      fullPath: '/damnificados/'
      preLoaderRoute: typeof DamnificadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damnificados/informal': {
      id: '/damnificados/informal'
      path: '/damnificados/informal'
      fullPath: '/damnificados/informal'
      preLoaderRoute: typeof DamnificadosInformalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damnificados/candidato': {
      id: '/damnificados/candidato'
      path: '/damnificados/candidato'
      fullPath: '/damnificados/candidato'
      preLoaderRoute: typeof DamnificadosCandidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/candidatos': {
      id: '/api/public/candidatos'
      path: '/api/public/candidatos'
      fullPath: '/api/public/candidatos'
      preLoaderRoute: typeof ApiPublicCandidatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cv/$submissionId/$filename': {
      id: '/api/public/cv/$submissionId/$filename'
      path: '/api/public/cv/$submissionId/$filename'
      fullPath: '/api/public/cv/$submissionId/$filename'
      preLoaderRoute: typeof ApiPublicCvSubmissionIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresasRoute: EmpresasRoute,
  GuiaRoute: GuiaRoute,
  DamnificadosCandidatoRoute: DamnificadosCandidatoRoute,
  DamnificadosInformalRoute: DamnificadosInformalRoute,
  DamnificadosIndexRoute: DamnificadosIndexRoute,
  ApiPublicCandidatosRoute: ApiPublicCandidatosRoute,
  ApiPublicCvSubmissionIdFilenameRoute: ApiPublicCvSubmissionIdFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
