ALTER TABLE public.busquedas
  ADD COLUMN IF NOT EXISTS nombre_contacto text,
  ADD COLUMN IF NOT EXISTS empresa text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS telefono_contacto text,
  ADD COLUMN IF NOT EXISTS cargo_contacto text,
  ADD COLUMN IF NOT EXISTS posicion_buscada text,
  ADD COLUMN IF NOT EXISTS seniority text,
  ADD COLUMN IF NOT EXISTS skills_requeridos text,
  ADD COLUMN IF NOT EXISTS skills_deseables text,
  ADD COLUMN IF NOT EXISTS anos_experiencia_minimos integer,
  ADD COLUMN IF NOT EXISTS industria_preferida text,
  ADD COLUMN IF NOT EXISTS modalidad text,
  ADD COLUMN IF NOT EXISTS genero_buscado text,
  ADD COLUMN IF NOT EXISTS num_vacantes integer,
  ADD COLUMN IF NOT EXISTS ubicacion text,
  ADD COLUMN IF NOT EXISTS rango_salarial text,
  ADD COLUMN IF NOT EXISTS descripcion_rol text,
  ADD COLUMN IF NOT EXISTS estado text DEFAULT 'pendiente';